export const START = '_START';
export const SUCCESS = '_SUCCESS';
export const FAIL = '_FAIL';

export const LOAD_HOUSES_LIST = 'LOAD_HOUSES_LIST';
export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';

export const LOAD_HOUSE_ITEM = 'LOAD_HOUSE_ITEM';
export const SET_HOUSE_ITEM = 'SET_HOUSE_ITEM';

export const SENDING_INVITATION = 'SENDING_INVITATION';
export const HIDE_INVITATION_ALERT = 'HIDE_INVITATION_ALERT';

export const CHANGE_DATE = 'CHANGE_DATE';
export const CHANGE_DATE_DAYS = 'CHANGE_DATE_DAYS';
